version: '3.3'

services:
  postgres:
    image: postgres:latest
    shm_size: 1g
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: trav
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - postgres_data:/var/lib/postgres

volumes:
  postgres_data: {}